version: 0.0
os: linux
files:
  - source: /
    destination: /Users/art/Documents/tampoon.net
permissions:
  - object: /Users/art/Documents/tampoon.net
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
